<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Logistic Regression | Statistical Analysis Using RStudio</title>
  <meta name="description" content="R Workshop 2021, PPSP, USM." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Logistic Regression | Statistical Analysis Using RStudio" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="your book url like https://wnarifin.gtihub.io" />
  
  <meta property="og:description" content="R Workshop 2021, PPSP, USM." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Logistic Regression | Statistical Analysis Using RStudio" />
  
  <meta name="twitter:description" content="R Workshop 2021, PPSP, USM." />
  

<meta name="author" content="Wan Nor Arifin" />


<meta name="date" content="2021-10-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="linear-regression.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Analysis Using RStudio</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>1</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="linear-regression.html"><a href="linear-regression.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="linear-regression.html"><a href="linear-regression.html#preliminaries"><i class="fa fa-check"></i><b>1.2</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="linear-regression.html"><a href="linear-regression.html#library"><i class="fa fa-check"></i><b>1.2.1</b> Library</a></li>
<li class="chapter" data-level="1.2.2" data-path="linear-regression.html"><a href="linear-regression.html#data"><i class="fa fa-check"></i><b>1.2.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="linear-regression.html"><a href="linear-regression.html#simple-linear-regression-slr"><i class="fa fa-check"></i><b>1.3</b> Simple linear regression (SLR)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="linear-regression.html"><a href="linear-regression.html#about-slr"><i class="fa fa-check"></i><b>1.3.1</b> About SLR</a></li>
<li class="chapter" data-level="1.3.2" data-path="linear-regression.html"><a href="linear-regression.html#data-exploration"><i class="fa fa-check"></i><b>1.3.2</b> Data exploration</a></li>
<li class="chapter" data-level="1.3.3" data-path="linear-regression.html"><a href="linear-regression.html#fit-univariable-slr"><i class="fa fa-check"></i><b>1.3.3</b> Fit Univariable SLR</a></li>
<li class="chapter" data-level="1.3.4" data-path="linear-regression.html"><a href="linear-regression.html#interpretation"><i class="fa fa-check"></i><b>1.3.4</b> Interpretation</a></li>
<li class="chapter" data-level="1.3.5" data-path="linear-regression.html"><a href="linear-regression.html#model-equation"><i class="fa fa-check"></i><b>1.3.5</b> Model equation</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="linear-regression.html"><a href="linear-regression.html#multiple-linear-regression-mlr"><i class="fa fa-check"></i><b>1.4</b> Multiple linear regression (MLR)</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="linear-regression.html"><a href="linear-regression.html#about-mlr"><i class="fa fa-check"></i><b>1.4.1</b> About MLR</a></li>
<li class="chapter" data-level="1.4.2" data-path="linear-regression.html"><a href="linear-regression.html#data-exploration-1"><i class="fa fa-check"></i><b>1.4.2</b> Data exploration</a></li>
<li class="chapter" data-level="1.4.3" data-path="linear-regression.html"><a href="linear-regression.html#variable-selection"><i class="fa fa-check"></i><b>1.4.3</b> Variable selection</a></li>
<li class="chapter" data-level="1.4.4" data-path="linear-regression.html"><a href="linear-regression.html#model-fit-assessment-residuals"><i class="fa fa-check"></i><b>1.4.4</b> Model fit assessment: Residuals</a></li>
<li class="chapter" data-level="1.4.5" data-path="linear-regression.html"><a href="linear-regression.html#interpretation-1"><i class="fa fa-check"></i><b>1.4.5</b> Interpretation</a></li>
<li class="chapter" data-level="1.4.6" data-path="linear-regression.html"><a href="linear-regression.html#model-equation-1"><i class="fa fa-check"></i><b>1.4.6</b> Model equation</a></li>
<li class="chapter" data-level="1.4.7" data-path="linear-regression.html"><a href="linear-regression.html#prediction"><i class="fa fa-check"></i><b>1.4.7</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="linear-regression.html"><a href="linear-regression.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>2</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="logistic-regression.html"><a href="logistic-regression.html#odds-ratio-vs-relative-risk"><i class="fa fa-check"></i><b>2.2</b> Odds ratio vs relative risk</a></li>
<li class="chapter" data-level="2.3" data-path="logistic-regression.html"><a href="logistic-regression.html#preliminaries-1"><i class="fa fa-check"></i><b>2.3</b> Preliminaries</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#library-1"><i class="fa fa-check"></i><b>2.3.1</b> Library</a></li>
<li class="chapter" data-level="2.3.2" data-path="logistic-regression.html"><a href="logistic-regression.html#data-1"><i class="fa fa-check"></i><b>2.3.2</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="logistic-regression.html"><a href="logistic-regression.html#simple-logistic-regression-slogr"><i class="fa fa-check"></i><b>2.4</b> Simple logistic regression (SLogR)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#about-slogr"><i class="fa fa-check"></i><b>2.4.1</b> About SLogR</a></li>
<li class="chapter" data-level="2.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#data-exploration-2"><i class="fa fa-check"></i><b>2.4.2</b> Data exploration</a></li>
<li class="chapter" data-level="2.4.3" data-path="logistic-regression.html"><a href="logistic-regression.html#fit-univariable-slogr"><i class="fa fa-check"></i><b>2.4.3</b> Fit Univariable SLogR</a></li>
<li class="chapter" data-level="2.4.4" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-2"><i class="fa fa-check"></i><b>2.4.4</b> Interpretation</a></li>
<li class="chapter" data-level="2.4.5" data-path="logistic-regression.html"><a href="logistic-regression.html#model-equation-2"><i class="fa fa-check"></i><b>2.4.5</b> Model equation</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="logistic-regression.html"><a href="logistic-regression.html#multiple-logistic-regression-mlogr"><i class="fa fa-check"></i><b>2.5</b> Multiple logistic regression (MLogR)</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="logistic-regression.html"><a href="logistic-regression.html#data-exploration-3"><i class="fa fa-check"></i><b>2.5.1</b> Data exploration</a></li>
<li class="chapter" data-level="2.5.2" data-path="logistic-regression.html"><a href="logistic-regression.html#variable-selection-1"><i class="fa fa-check"></i><b>2.5.2</b> Variable selection</a></li>
<li class="chapter" data-level="2.5.3" data-path="logistic-regression.html"><a href="logistic-regression.html#model-fit-assessment"><i class="fa fa-check"></i><b>2.5.3</b> Model fit assessment</a></li>
<li class="chapter" data-level="2.5.4" data-path="logistic-regression.html"><a href="logistic-regression.html#interpretation-3"><i class="fa fa-check"></i><b>2.5.4</b> Interpretation</a></li>
<li class="chapter" data-level="2.5.5" data-path="logistic-regression.html"><a href="logistic-regression.html#model-equations"><i class="fa fa-check"></i><b>2.5.5</b> Model equations</a></li>
<li class="chapter" data-level="2.5.6" data-path="logistic-regression.html"><a href="logistic-regression.html#prediction-1"><i class="fa fa-check"></i><b>2.5.6</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="logistic-regression.html"><a href="logistic-regression.html#exercises-1"><i class="fa fa-check"></i><b>2.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Analysis Using RStudio</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Logistic Regression</h1>
<div id="introduction-1" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Introduction</h2>
<ol style="list-style-type: decimal">
<li><p>Statistical method to model relationship between:</p>
<ul>
<li>outcome: binary categorical variable.</li>
<li>predictors/independent variables: numerical, categorical variables.</li>
</ul></li>
<li><p>A type of Generalized Linear Models (GLMs).</p></li>
<li><p>Basically, the relationship is structured as follows,</p></li>
</ol>
<p><span class="math display">\[binary\ outcome = numerical\ predictors + categorical\ predictors\]</span></p>
<p>more accurately, the <em>logistic</em> relationship structure,</p>
<p><span class="math display">\[log_e\bigg({proportion \over 1 - proportion}\bigg) = numerical\ predictors + categorical\ predictors\]</span>
We turned the binary outcome into proportion (<span class="math inline">\(p\)</span>) of having the outcome. <span class="math inline">\(log_e\)</span> is the <em>natural log</em>, sometimes written as <em>ln</em>.</p>
<p>The part, <span class="math inline">\(\frac{p}{1-p}\)</span> is known as <em>odds</em>.</p>
</div>
<div id="odds-ratio-vs-relative-risk" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Odds ratio vs relative risk</h2>
<p>Association analysis for cross-tabulation of a binary factor and its outcome can be expressed as odds ratio.</p>
<ul>
<li>Odds is a measure of chance of disease occurence in a specified group,
<span class="math display">\[Odds = \frac{n_{disease}}{n_{no\ disease}}\]</span></li>
<li>Odds ratio, OR is the ratio between the odds of two groups; the group with the risk factor and the group without the risk factor,
<span class="math display">\[Odds\ ratio, OR = \frac{Odds_{factor}}{Odds_{no\ factor}}\]</span></li>
</ul>
<p>Odds ratio can be calculated for cohort, cross-sectional and case-control studied because it does not imply a cause-effect association, but only plain association.</p>
<p>In epidemiology, it is common to describe the association between a risk factor and a disease in term of risk and relative risk.</p>
<ul>
<li>Risk is a measure of chance of disease occurence in a specified group, calculated as
<span class="math display">\[Risk = \frac{n_{disease}}{n_{group}}\]</span></li>
<li>Relative risk is the ration between the risk in the group with the factor and the risk in the group without the risk factor,
<span class="math display">\[Relative\ risk, RR = \frac{Risk_{factor}}{Risk_{no\ factor}}\]</span>
It is only approriate to calculate risk and relative risk for cohort studies, because the cause-effect relationship is well defined.</li>
</ul>
<p>OR is a good approximation of RR whenever the disease is rare. Rare diseases are commonly studied using case-control studies, thus the use of ORs are justified.</p>
<p>As an example, we can calculate odds, OR, risk and RR from the following table.</p>
<table>
<caption>Smoker vs lung cancer</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">Lung cancer</th>
<th align="right">No lung cancer</th>
<th align="right">Marginal total</th>
<th align="right">Odds</th>
<th align="right">Risk</th>
<th align="right"></th>
<th align="right"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smoker</td>
<td align="right">20</td>
<td align="right">12</td>
<td align="right">32</td>
<td align="right">20/12 = 1.667</td>
<td align="right">20/32 = 0.625</td>
<td align="right"></td>
<td align="right"></td>
</tr>
<tr class="even">
<td>Non smoker</td>
<td align="right">95</td>
<td align="right">73</td>
<td align="right">168</td>
<td align="right">95/73 = 1.301</td>
<td align="right">95/168 = 0.565</td>
<td align="right"></td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>Thus OR and RR equal,
<span class="math display">\[OR = 1.667/1.301 = 1.281\]</span>
<span class="math display">\[RR = 0.625/0.565 = 1.106\]</span></p>
</div>
<div id="preliminaries-1" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Preliminaries</h2>
<div id="library-1" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Library</h3>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="logistic-regression.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># official CRAN</span></span>
<span id="cb93-2"><a href="logistic-regression.html#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(foreign)</span>
<span id="cb93-3"><a href="logistic-regression.html#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb93-4"><a href="logistic-regression.html#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb93-5"><a href="logistic-regression.html#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb93-6"><a href="logistic-regression.html#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb93-7"><a href="logistic-regression.html#cb93-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb93-8"><a href="logistic-regression.html#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb93-9"><a href="logistic-regression.html#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsq)</span>
<span id="cb93-10"><a href="logistic-regression.html#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb93-11"><a href="logistic-regression.html#cb93-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ResourceSelection)</span></code></pre></div>
<pre><code>## ResourceSelection 0.3-5   2019-07-22</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="logistic-regression.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># custom function</span></span>
<span id="cb95-2"><a href="logistic-regression.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co"># desc_cat()</span></span>
<span id="cb95-3"><a href="logistic-regression.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;https://raw.githubusercontent.com/wnarifin/medicalstats-in-R/master/functions/desc_cat_fun.R&quot;</span>)</span></code></pre></div>
</div>
<div id="data-1" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Data</h3>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="logistic-regression.html#cb96-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="ot">=</span> <span class="fu">read.dta</span>(<span class="st">&quot;coronary.dta&quot;</span>)</span>
<span id="cb96-2"><a href="logistic-regression.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coronary)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    200 obs. of  9 variables:
##  $ id    : num  1 14 56 61 62 64 69 108 112 134 ...
##  $ cad   : Factor w/ 2 levels &quot;no cad&quot;,&quot;cad&quot;: 1 1 1 1 1 1 2 1 1 1 ...
##  $ sbp   : num  106 130 136 138 115 124 110 112 138 104 ...
##  $ dbp   : num  68 78 84 100 85 72 80 70 85 70 ...
##  $ chol  : num  6.57 6.33 5.97 7.04 6.66 ...
##  $ age   : num  60 34 36 45 53 43 44 50 43 48 ...
##  $ bmi   : num  38.9 37.8 40.5 37.6 40.3 ...
##  $ race  : Factor w/ 3 levels &quot;malay&quot;,&quot;chinese&quot;,..: 3 1 1 1 3 1 1 2 2 2 ...
##  $ gender: Factor w/ 2 levels &quot;woman&quot;,&quot;man&quot;: 1 1 1 1 2 2 2 1 1 2 ...
##  - attr(*, &quot;datalabel&quot;)= chr &quot;Written by R.              &quot;
##  - attr(*, &quot;time.stamp&quot;)= chr &quot;&quot;
##  - attr(*, &quot;formats&quot;)= chr  &quot;%9.0g&quot; &quot;%9.0g&quot; &quot;%9.0g&quot; &quot;%9.0g&quot; ...
##  - attr(*, &quot;types&quot;)= int  100 108 100 100 100 100 100 108 108
##  - attr(*, &quot;val.labels&quot;)= chr  &quot;&quot; &quot;cad&quot; &quot;&quot; &quot;&quot; ...
##  - attr(*, &quot;var.labels&quot;)= chr  &quot;id&quot; &quot;cad&quot; &quot;sbp&quot; &quot;dbp&quot; ...
##  - attr(*, &quot;version&quot;)= int 7
##  - attr(*, &quot;label.table&quot;)=List of 3
##   ..$ cad   : Named int  1 2
##   .. ..- attr(*, &quot;names&quot;)= chr  &quot;no cad&quot; &quot;cad&quot;
##   ..$ race  : Named int  1 2 3
##   .. ..- attr(*, &quot;names&quot;)= chr  &quot;malay&quot; &quot;chinese&quot; &quot;indian&quot;
##   ..$ gender: Named int  1 2
##   .. ..- attr(*, &quot;names&quot;)= chr  &quot;woman&quot; &quot;man&quot;</code></pre>
<div id="descriptive-statistics-3" class="section level4 unnumbered">
<h4>Descriptive statistics</h4>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="logistic-regression.html#cb98-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>id) <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="logistic-regression.html#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(<span class="at">by =</span> cad,</span>
<span id="cb98-3"><a href="logistic-regression.html#cb98-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">statistic =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="st">&quot;{mean} ({sd})&quot;</span>, </span>
<span id="cb98-4"><a href="logistic-regression.html#cb98-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">digits =</span> <span class="fu">all_continuous</span>() <span class="sc">~</span> <span class="dv">1</span>)</span></code></pre></div>
<div id="ybrpoqzivo" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ybrpoqzivo .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ybrpoqzivo .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ybrpoqzivo .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ybrpoqzivo .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ybrpoqzivo .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ybrpoqzivo .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ybrpoqzivo .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ybrpoqzivo .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ybrpoqzivo .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ybrpoqzivo .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ybrpoqzivo .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ybrpoqzivo .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ybrpoqzivo .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ybrpoqzivo .gt_from_md > :first-child {
  margin-top: 0;
}

#ybrpoqzivo .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ybrpoqzivo .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ybrpoqzivo .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ybrpoqzivo .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ybrpoqzivo .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ybrpoqzivo .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ybrpoqzivo .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ybrpoqzivo .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ybrpoqzivo .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ybrpoqzivo .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ybrpoqzivo .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ybrpoqzivo .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ybrpoqzivo .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ybrpoqzivo .gt_left {
  text-align: left;
}

#ybrpoqzivo .gt_center {
  text-align: center;
}

#ybrpoqzivo .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ybrpoqzivo .gt_font_normal {
  font-weight: normal;
}

#ybrpoqzivo .gt_font_bold {
  font-weight: bold;
}

#ybrpoqzivo .gt_font_italic {
  font-style: italic;
}

#ybrpoqzivo .gt_super {
  font-size: 65%;
}

#ybrpoqzivo .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>no cad</strong>, N = 163<sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>cad</strong>, N = 37<sup class="gt_footnote_marks">1</sup></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">sbp</td>
<td class="gt_row gt_center">127.8 (19.1)</td>
<td class="gt_row gt_center">140.5 (19.7)</td></tr>
    <tr><td class="gt_row gt_left">dbp</td>
<td class="gt_row gt_center">80.8 (12.6)</td>
<td class="gt_row gt_center">89.0 (12.2)</td></tr>
    <tr><td class="gt_row gt_left">chol</td>
<td class="gt_row gt_center">6.1 (1.2)</td>
<td class="gt_row gt_center">6.6 (1.2)</td></tr>
    <tr><td class="gt_row gt_left">age</td>
<td class="gt_row gt_center">46.8 (7.4)</td>
<td class="gt_row gt_center">49.7 (6.7)</td></tr>
    <tr><td class="gt_row gt_left">bmi</td>
<td class="gt_row gt_center">37.6 (2.5)</td>
<td class="gt_row gt_center">36.9 (3.4)</td></tr>
    <tr><td class="gt_row gt_left">race</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">malay</td>
<td class="gt_row gt_center">60 (37%)</td>
<td class="gt_row gt_center">13 (35%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">chinese</td>
<td class="gt_row gt_center">52 (32%)</td>
<td class="gt_row gt_center">12 (32%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">indian</td>
<td class="gt_row gt_center">51 (31%)</td>
<td class="gt_row gt_center">12 (32%)</td></tr>
    <tr><td class="gt_row gt_left">gender</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">woman</td>
<td class="gt_row gt_center">87 (53%)</td>
<td class="gt_row gt_center">13 (35%)</td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">man</td>
<td class="gt_row gt_center">76 (47%)</td>
<td class="gt_row gt_center">24 (65%)</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="3">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          Mean (SD); n (%)
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
</div>
</div>
</div>
<div id="simple-logistic-regression-slogr" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Simple logistic regression (SLogR)</h2>
<div id="about-slogr" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> About SLogR</h3>
<ol style="list-style-type: decimal">
<li><p>Model relatioship between:</p>
<ul>
<li>outcome: binary categorical variable.</li>
<li>a predictor: numerical or binary categorical variable.</li>
</ul></li>
<li><p>Formula,
<span class="math display">\[log_e\bigg(\frac{p}{1-p}\bigg) = intercept + coefficient \times numerical/binary\ predictor\]</span>
or in a proper equation form,
<span class="math display">\[log_e\bigg(\frac{p}{1-p}\bigg) = \beta_0 + \beta_1x_1\]</span></p></li>
<li><p>Odds ratio is easily obtained from a logistic regression,</p></li>
</ol>
<p><span class="math display">\[OR_1 = e^{\beta_1}\]</span>
4. <span class="math inline">\(p\)</span> – proportion/probability. To obtain <span class="math inline">\(p\)</span>,</p>
<p><span class="math display">\[p = \frac{e^{\beta_0 + \beta_1x_1}}{1 + e^{\beta_0 + \beta_1x_1}}\]</span>
But as we will see later, this can be easily obtained in R.</p>
</div>
<div id="data-exploration-2" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Data exploration</h3>
<div id="descriptive-statistics-4" class="section level4 unnumbered">
<h4>Descriptive statistics</h4>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="logistic-regression.html#cb99-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="sc">%&gt;%</span> <span class="fu">select</span>(gender, cad) <span class="sc">%&gt;%</span> <span class="fu">desc_cat</span>()</span></code></pre></div>
<pre><code>## $gender
##   Variable Label   n Percent
## 1   gender woman 100      50
## 2        -   man 100      50
## 
## $cad
##   Variable  Label   n Percent
## 1      cad no cad 163    81.5
## 2        -    cad  37    18.5</code></pre>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="logistic-regression.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(coronary, <span class="fu">table</span>(gender, cad)) <span class="sc">%&gt;%</span> <span class="fu">print</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="logistic-regression.html#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prop.table</span>(<span class="at">margin =</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##        cad
## gender  no cad cad
##   woman     87  13
##   man       76  24</code></pre>
<pre><code>##        cad
## gender    no cad      cad
##   woman 53.37423 35.13514
##   man   46.62577 64.86486</code></pre>
</div>
</div>
<div id="fit-univariable-slogr" class="section level3" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Fit Univariable SLogR</h3>
<p>Fit model,</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="logistic-regression.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cad ~ gender</span></span>
<span id="cb104-2"><a href="logistic-regression.html#cb104-2" aria-hidden="true" tabindex="-1"></a>slg_cad <span class="ot">=</span> <span class="fu">glm</span>(cad <span class="sc">~</span> gender, <span class="at">data =</span> coronary, <span class="at">family =</span> binomial)</span>
<span id="cb104-3"><a href="logistic-regression.html#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slg_cad)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.7409  -0.7409  -0.5278  -0.5278   2.0200  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.9010     0.2973  -6.393 1.63e-10 ***
## genderman     0.7483     0.3785   1.977    0.048 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 187.49  on 198  degrees of freedom
## AIC: 191.49
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="logistic-regression.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(slg_cad, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>)  <span class="co"># OR</span></span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   term        estimate std.error statistic  p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)    0.149     0.297     -6.39 1.63e-10   0.0796     0.258
## 2 genderman      2.11      0.378      1.98 4.80e- 2   1.02       4.55</code></pre>
<p>Focus on:</p>
<ul>
<li>Coefficient, <span class="math inline">\(\beta\)</span> and OR.</li>
<li>95% CI.</li>
<li><em>P</em>-value.</li>
</ul>
</div>
<div id="interpretation-2" class="section level3" number="2.4.4">
<h3><span class="header-section-number">2.4.4</span> Interpretation</h3>
<p>We are most interested in the OR,</p>
<ul>
<li>Man is at 2.11 odds of having coronary artery disease (CAD) as compared to woman.</li>
</ul>
<p>Be careful with the terms; odds vs risk!</p>
</div>
<div id="model-equation-2" class="section level3" number="2.4.5">
<h3><span class="header-section-number">2.4.5</span> Model equation</h3>
<p><span class="math display">\[log_e\bigg(\frac{p_{cad}}{1-p_{cad}}\bigg) = -1.90 + 0.75 \times gender\ (man)\]</span></p>
<p><span class="math display">\[p_{cad} = \frac{e^{-1.9 + 0.75 \times gender\ (man)}}{1 + {e^{-1.90 + 0.75 \times gender\ (man)}}}\]</span>
<em>Note</em>: Don’t scratch your head.</p>
</div>
</div>
<div id="multiple-logistic-regression-mlogr" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Multiple logistic regression (MLogR)</h2>
<ol style="list-style-type: decimal">
<li><p>Model relatioship between:</p>
<ul>
<li>outcome: binary categorical variable.</li>
<li>predictors: numerical, categorical variables.</li>
</ul></li>
<li><p>Formula,
<span class="math display">\[\begin{aligned}
log_e\bigg(\frac{p}{1-p}\bigg) = &amp;\ intercept + coefficients \times numerical\ predictors \\
&amp; + coefficients \times categorical\ predictors
\end{aligned}\]</span></p></li>
</ol>
<p>or in a nicer form,
<span class="math display">\[log_e\bigg(\frac{p}{1-p}\bigg) = \beta_0 + \beta_1x_1 + \beta_2x_2 + ... + \beta_kx_k\]</span>
where we have <em>k</em> predictors.</p>
<p>Whenever the predictor is a categorical variable with more than two levels, remember to consider dummy (binary) variable(s).</p>
<div id="data-exploration-3" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Data exploration</h3>
<div id="descriptive-statistics-5" class="section level4 unnumbered">
<h4>Descriptive statistics</h4>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="logistic-regression.html#cb108-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>id, <span class="sc">-</span>cad, <span class="sc">-</span>race, <span class="sc">-</span>gender) <span class="sc">%&gt;%</span> <span class="fu">describeBy</span>(., coronary<span class="sc">$</span>cad)  <span class="co"># numerical</span></span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## group: no cad
##      vars   n   mean    sd median trimmed   mad   min    max range  skew
## sbp     1 163 127.84 19.14 124.00  126.33 17.79 88.00 187.00 99.00  0.68
## dbp     2 163  80.80 12.61  80.00   80.11 14.83 56.00 120.00 64.00  0.50
## chol    3 163   6.10  1.17   6.05    6.07  1.06  4.00   9.35  5.35  0.23
## age     4 163  46.79  7.40  47.00   46.65  8.90 32.00  62.00 30.00  0.12
## bmi     5 163  37.58  2.48  38.00   37.82  2.08 28.99  41.20 12.21 -0.91
##      kurtosis   se
## sbp      0.04 1.50
## dbp     -0.12 0.99
## chol    -0.29 0.09
## age     -0.75 0.58
## bmi      0.72 0.19
## ------------------------------------------------------------ 
## group: cad
##      vars  n   mean    sd median trimmed   mad    min    max range  skew
## sbp     1 37 140.49 19.67 138.00  140.45 25.20 100.00 178.00 78.00 -0.02
## dbp     2 37  88.97 12.17  90.00   88.58 14.83  70.00 114.00 44.00  0.25
## chol    3 37   6.65  1.17   6.66    6.65  0.90   4.12   9.05  4.92 -0.01
## age     4 37  49.70  6.66  50.00   49.84  7.41  35.00  61.00 26.00 -0.18
## bmi     5 37  36.86  3.39  37.14   36.69  3.23  31.00  45.03 14.03  0.34
##      kurtosis   se
## sbp     -1.06 3.23
## dbp     -1.01 2.00
## chol    -0.28 0.19
## age     -0.88 1.10
## bmi     -0.22 0.56</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="logistic-regression.html#cb110-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="sc">%&gt;%</span> <span class="fu">select</span>(race, gender) <span class="sc">%&gt;%</span> <span class="fu">by</span>(., coronary<span class="sc">$</span>cad, desc_cat)  <span class="co"># categorical</span></span></code></pre></div>
<pre><code>## coronary$cad: no cad
## $race
##   Variable   Label  n  Percent
## 1     race   malay 60 36.80982
## 2        - chinese 52 31.90184
## 3        -  indian 51 31.28834
## 
## $gender
##   Variable Label  n  Percent
## 1   gender woman 87 53.37423
## 2        -   man 76 46.62577
## 
## ------------------------------------------------------------ 
## coronary$cad: cad
## $race
##   Variable   Label  n  Percent
## 1     race   malay 13 35.13514
## 2        - chinese 12 32.43243
## 3        -  indian 12 32.43243
## 
## $gender
##   Variable Label  n  Percent
## 1   gender woman 13 35.13514
## 2        -   man 24 64.86486</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="logistic-regression.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or just use tbl_summary()</span></span></code></pre></div>
</div>
<div id="plots-2" class="section level4 unnumbered">
<h4>Plots</h4>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="logistic-regression.html#cb113-1" aria-hidden="true" tabindex="-1"></a>coronary <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>id, <span class="sc">-</span>cad) <span class="sc">%&gt;%</span> <span class="fu">by</span>(., coronary<span class="sc">$</span>cad, ggpairs)  <span class="co"># or using built-in graphics</span></span></code></pre></div>
<pre><code>## coronary$cad: no cad</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre><code>## ------------------------------------------------------------ 
## coronary$cad: cad</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-34-2.png" width="672" /></p>
</div>
</div>
<div id="variable-selection-1" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Variable selection</h3>
<div id="fit-univariable-slogr-1" class="section level4 unnumbered">
<h4>Fit Univariable SLogR</h4>
<p>Perform SLogR for <code>sbp, dbp, chol, age, bmi, race</code> and <code>gender</code> on your own. Now, we want to determine which variables are worthwhile to include in the multivariable models.</p>
<p>We want to screen variables with <em>P</em>-values &lt; 0.25 to be included in MLogR. Obtaining the <em>P</em>-values for each variable is easy by LR test,</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="logistic-regression.html#cb118-1" aria-hidden="true" tabindex="-1"></a>slg_cad0 <span class="ot">=</span> <span class="fu">glm</span>(cad <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> coronary, <span class="at">family =</span> binomial)</span>
<span id="cb118-2"><a href="logistic-regression.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(slg_cad0)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ 1, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.6396  -0.6396  -0.6396  -0.6396   1.8371  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -1.4828     0.1821  -8.143 3.86e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 191.56  on 199  degrees of freedom
## AIC: 193.56
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="logistic-regression.html#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">add1</span>(slg_cad0, <span class="at">scope =</span> <span class="sc">~</span> sbp <span class="sc">+</span> dbp <span class="sc">+</span> chol <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> race <span class="sc">+</span> gender, <span class="at">test =</span> <span class="st">&quot;LRT&quot;</span>)</span></code></pre></div>
<pre><code>## Single term additions
## 
## Model:
## cad ~ 1
##        Df Deviance    AIC     LRT  Pr(&gt;Chi)    
## &lt;none&gt;      191.56 193.56                      
## sbp     1   179.62 183.62 11.9339 0.0005512 ***
## dbp     1   179.62 183.62 11.9333 0.0005514 ***
## chol    1   185.04 189.04  6.5187 0.0106747 *  
## age     1   186.72 190.72  4.8346 0.0278945 *  
## bmi     1   189.38 193.38  2.1811 0.1397120    
## race    2   191.52 197.52  0.0385 0.9809448    
## gender  1   187.49 191.49  4.0631 0.0438292 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>All variables are &lt; .25 except <code>race</code>.</p>
</div>
<div id="fit-multivariable-mlogr" class="section level4 unnumbered">
<h4>Fit Multivariable MLogR</h4>
<p>Perform MLogR with the selected variables. Modeling considerations:</p>
<ul>
<li><code>race</code> not included, <em>P</em>-value &gt; 0.25</li>
<li><code>sbp</code> not included, redundant.</li>
</ul>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="logistic-regression.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co"># all</span></span>
<span id="cb122-2"><a href="logistic-regression.html#cb122-2" aria-hidden="true" tabindex="-1"></a>mlg_cad <span class="ot">=</span> <span class="fu">glm</span>(cad <span class="sc">~</span> dbp <span class="sc">+</span> chol <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> gender, </span>
<span id="cb122-3"><a href="logistic-regression.html#cb122-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> coronary, <span class="at">family =</span> binomial)</span>
<span id="cb122-4"><a href="logistic-regression.html#cb122-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + chol + age + bmi + gender, family = binomial, 
##     data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3847  -0.6228  -0.5055  -0.3562   2.3244  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -5.35585    3.22561  -1.660   0.0968 .
## dbp          0.03940    0.01678   2.348   0.0189 *
## chol         0.14300    0.18611   0.768   0.4423  
## age          0.01539    0.03081   0.500   0.6173  
## bmi         -0.04021    0.06824  -0.589   0.5557  
## genderman    0.69514    0.40232   1.728   0.0840 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 173.70  on 194  degrees of freedom
## AIC: 185.7
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>At this point, focus on:</p>
<ul>
<li>Coefficients, <span class="math inline">\(\beta\)</span>s.</li>
<li><em>P</em>-values.</li>
</ul>
</div>
<div id="stepwise-1" class="section level4 unnumbered">
<h4>Stepwise</h4>
<p>We proceed with stepwise automatic selection,</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="logistic-regression.html#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># both</span></span>
<span id="cb124-2"><a href="logistic-regression.html#cb124-2" aria-hidden="true" tabindex="-1"></a>mlg_cad_stepboth <span class="ot">=</span> <span class="fu">step</span>(mlg_cad, <span class="at">direction =</span> <span class="st">&quot;both&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=185.7
## cad ~ dbp + chol + age + bmi + gender
## 
##          Df Deviance    AIC
## - age     1   173.95 183.95
## - bmi     1   174.05 184.05
## - chol    1   174.29 184.29
## &lt;none&gt;        173.70 185.70
## - gender  1   176.77 186.77
## - dbp     1   179.46 189.46
## 
## Step:  AIC=183.95
## cad ~ dbp + chol + bmi + gender
## 
##          Df Deviance    AIC
## - bmi     1   174.26 182.26
## - chol    1   174.80 182.80
## &lt;none&gt;        173.95 183.95
## - gender  1   177.40 185.40
## + age     1   173.70 185.70
## - dbp     1   180.91 188.91
## 
## Step:  AIC=182.26
## cad ~ dbp + chol + gender
## 
##          Df Deviance    AIC
## - chol    1   175.21 181.21
## &lt;none&gt;        174.26 182.26
## - gender  1   177.86 183.86
## + bmi     1   173.95 183.95
## + age     1   174.05 184.05
## - dbp     1   181.87 187.87
## 
## Step:  AIC=181.2
## cad ~ dbp + gender
## 
##          Df Deviance    AIC
## &lt;none&gt;        175.21 181.21
## + chol    1   174.26 182.26
## + age     1   174.74 182.74
## + bmi     1   174.80 182.80
## - gender  1   179.62 183.62
## - dbp     1   187.49 191.49</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="logistic-regression.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_stepboth)  <span class="co"># cad ~ dbp + gender</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="logistic-regression.html#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># forward</span></span>
<span id="cb128-2"><a href="logistic-regression.html#cb128-2" aria-hidden="true" tabindex="-1"></a>mlg_cad_stepforward <span class="ot">=</span> <span class="fu">step</span>(slg_cad0, </span>
<span id="cb128-3"><a href="logistic-regression.html#cb128-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">scope =</span> <span class="sc">~</span> dbp <span class="sc">+</span> chol <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> gender, </span>
<span id="cb128-4"><a href="logistic-regression.html#cb128-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">direction =</span> <span class="st">&quot;forward&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=193.56
## cad ~ 1
## 
##          Df Deviance    AIC
## + dbp     1   179.62 183.62
## + chol    1   185.04 189.04
## + age     1   186.72 190.72
## + gender  1   187.49 191.49
## + bmi     1   189.38 193.38
## &lt;none&gt;        191.56 193.56
## 
## Step:  AIC=183.62
## cad ~ dbp
## 
##          Df Deviance    AIC
## + gender  1   175.21 181.21
## &lt;none&gt;        179.62 183.62
## + chol    1   177.86 183.86
## + age     1   178.50 184.50
## + bmi     1   178.98 184.98
## 
## Step:  AIC=181.2
## cad ~ dbp + gender
## 
##        Df Deviance    AIC
## &lt;none&gt;      175.21 181.21
## + chol  1   174.26 182.26
## + age   1   174.74 182.74
## + bmi   1   174.80 182.80</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="logistic-regression.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_stepforward)  <span class="co"># cad ~ dbp + gender</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="logistic-regression.html#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="co"># backward</span></span>
<span id="cb132-2"><a href="logistic-regression.html#cb132-2" aria-hidden="true" tabindex="-1"></a>mlg_cad_stepback <span class="ot">=</span> <span class="fu">step</span>(mlg_cad, <span class="at">direction =</span> <span class="st">&quot;backward&quot;</span>)</span></code></pre></div>
<pre><code>## Start:  AIC=185.7
## cad ~ dbp + chol + age + bmi + gender
## 
##          Df Deviance    AIC
## - age     1   173.95 183.95
## - bmi     1   174.05 184.05
## - chol    1   174.29 184.29
## &lt;none&gt;        173.70 185.70
## - gender  1   176.77 186.77
## - dbp     1   179.46 189.46
## 
## Step:  AIC=183.95
## cad ~ dbp + chol + bmi + gender
## 
##          Df Deviance    AIC
## - bmi     1   174.26 182.26
## - chol    1   174.80 182.80
## &lt;none&gt;        173.95 183.95
## - gender  1   177.40 185.40
## - dbp     1   180.91 188.91
## 
## Step:  AIC=182.26
## cad ~ dbp + chol + gender
## 
##          Df Deviance    AIC
## - chol    1   175.21 181.21
## &lt;none&gt;        174.26 182.26
## - gender  1   177.86 183.86
## - dbp     1   181.87 187.87
## 
## Step:  AIC=181.2
## cad ~ dbp + gender
## 
##          Df Deviance    AIC
## &lt;none&gt;        175.21 181.21
## - gender  1   179.62 183.62
## - dbp     1   187.49 191.49</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="logistic-regression.html#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_stepback)  <span class="co"># cad ~ dbp + gender</span></span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Our chosen model:</p>
<blockquote>
<p>cad ~ dbp + gender`</p>
</blockquote>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="logistic-regression.html#cb136-1" aria-hidden="true" tabindex="-1"></a>mlg_cad_sel <span class="ot">=</span> <span class="fu">glm</span>(cad <span class="sc">~</span> dbp <span class="sc">+</span> gender, <span class="at">data =</span> coronary, <span class="at">family =</span> binomial)</span>
<span id="cb136-2"><a href="logistic-regression.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_sel)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="logistic-regression.html#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(mlg_cad_sel, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 7
##   term        estimate std.error statistic    p.value conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)  -6.12      1.32       -4.65 0.00000334  -8.83     -3.64  
## 2 dbp           0.0495    0.0146      3.38 0.000717     0.0215    0.0793
## 3 genderman     0.806     0.391       2.06 0.0393       0.0538    1.60</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="logistic-regression.html#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl_regression</span>(mlg_cad_sel)</span></code></pre></div>
<div id="ermebxxsxr" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ermebxxsxr .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ermebxxsxr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ermebxxsxr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ermebxxsxr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ermebxxsxr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ermebxxsxr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ermebxxsxr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ermebxxsxr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ermebxxsxr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ermebxxsxr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ermebxxsxr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ermebxxsxr .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ermebxxsxr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ermebxxsxr .gt_from_md > :first-child {
  margin-top: 0;
}

#ermebxxsxr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ermebxxsxr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ermebxxsxr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ermebxxsxr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ermebxxsxr .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ermebxxsxr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ermebxxsxr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ermebxxsxr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ermebxxsxr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ermebxxsxr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ermebxxsxr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ermebxxsxr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ermebxxsxr .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ermebxxsxr .gt_left {
  text-align: left;
}

#ermebxxsxr .gt_center {
  text-align: center;
}

#ermebxxsxr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ermebxxsxr .gt_font_normal {
  font-weight: normal;
}

#ermebxxsxr .gt_font_bold {
  font-weight: bold;
}

#ermebxxsxr .gt_font_italic {
  font-style: italic;
}

#ermebxxsxr .gt_super {
  font-size: 65%;
}

#ermebxxsxr .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>log(OR)</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">dbp</td>
<td class="gt_row gt_center">0.05</td>
<td class="gt_row gt_center">0.02, 0.08</td>
<td class="gt_row gt_center"><0.001</td></tr>
    <tr><td class="gt_row gt_left">gender</td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">woman</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center">—</td>
<td class="gt_row gt_center"></td></tr>
    <tr><td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">man</td>
<td class="gt_row gt_center">0.81</td>
<td class="gt_row gt_center">0.05, 1.6</td>
<td class="gt_row gt_center">0.039</td></tr>
  </tbody>
  
  <tfoot>
    <tr class="gt_footnotes">
      <td colspan="4">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks">
            <em>1</em>
          </sup>
           
          OR = Odds Ratio, CI = Confidence Interval
          <br />
        </p>
      </td>
    </tr>
  </tfoot>
</table>
</div>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="logistic-regression.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rsq</span>(mlg_cad_sel)</span></code></pre></div>
<pre><code>## [1] 0.08189364</code></pre>
</div>
<div id="multicollinearity-mc-1" class="section level4 unnumbered">
<h4>Multicollinearity, MC</h4>
<p>Multicollinearity is the problem of redundant variables, in other words, high correlations between predictors. For logistic regression, this is checked by looking at the estimates and standard errors, SEs. Whenever SE is larger than the estimate, this may point to an MC problem. But how large is large? Relatively large, this is not mentioned specifically in <span class="citation"><a href="#ref-hosmer2013" role="doc-biblioref">Hosmer, Lemeshow, &amp; Sturdivant</a> (<a href="#ref-hosmer2013" role="doc-biblioref">2013</a>)</span>. My own guess is that the ratio between SE:estimate should be &lt; 1.</p>
<p>Sometimes, the estimates are unusually large, i.e. indicates very large ORs. This is illogical – also indicates an MC problem.</p>
<p>Again we look at our <code>mlg_cad_sel</code> model,</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="logistic-regression.html#cb143-1" aria-hidden="true" tabindex="-1"></a>cad <span class="sc">~</span> dbp <span class="sc">+</span> gender</span></code></pre></div>
<pre><code>## cad ~ dbp + gender</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="logistic-regression.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_sel)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Fortunately, all SEs &lt; estimates/coefficients.</p>
</div>
<div id="interaction-1" class="section level4 unnumbered">
<h4>Interaction, *</h4>
<p>Interaction is the predictor variable combination that necessitates the interpretation of regression coefficients separately based for each level of the predictor (e.g. separate analysis for male vs female). Again, this makes interpreting our analysis complicated. So, most of the time, we pray not to have interaction in our regression model.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="logistic-regression.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glm</span>(cad <span class="sc">~</span> dbp <span class="sc">*</span> gender, <span class="at">data =</span> coronary, <span class="at">family =</span> binomial))</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp * gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3876  -0.6677  -0.5317  -0.3306   2.4107  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)   -7.06999    2.50172  -2.826  0.00471 **
## dbp            0.06029    0.02807   2.148  0.03169 * 
## genderman      2.11719    2.91088   0.727  0.46702   
## dbp:genderman -0.01501    0.03288  -0.456  0.64815   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 174.99  on 196  degrees of freedom
## AIC: 182.99
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="logistic-regression.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># insig. dbp * gender</span></span></code></pre></div>
<p>There was no significant interaction to be included in out model.</p>
</div>
</div>
<div id="model-fit-assessment" class="section level3" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Model fit assessment</h3>
<p>There are three model fit assessment methods commonly done for logistic regression:</p>
<ol style="list-style-type: decimal">
<li>Hosmer-Lemeshow test.</li>
<li>Classification table.</li>
<li>Area Under the Curve (AUC) of Receiver Operating Characteristics (ROC) curve.</li>
</ol>
<p>Basically, we want to compare the real cad status (observed) against the predicted cad status and probability (as predicted by our logistic regression model).</p>
<ol style="list-style-type: decimal">
<li><p>Hosmer-Lemeshow test.</p>
<ul>
<li><em>P</em>-value &gt; 0.05 – Model (predicted counts) fit the data (observed counts).</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="logistic-regression.html#cb150-1" aria-hidden="true" tabindex="-1"></a>hl_cad <span class="ot">=</span> <span class="fu">hoslem.test</span>(mlg_cad_sel<span class="sc">$</span>y, mlg_cad_sel<span class="sc">$</span>fitted.values)</span>
<span id="cb150-2"><a href="logistic-regression.html#cb150-2" aria-hidden="true" tabindex="-1"></a>hl_cad</span></code></pre></div>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  mlg_cad_sel$y, mlg_cad_sel$fitted.values
## X-squared = 18.199, df = 8, p-value = 0.01978</code></pre>
<p><em>P</em>-value &lt; 0.05, the model does not fit (slightly). Ideally &gt; 0.05. Usually this happens because of small number of variables in the model.</p>
<p>Detailed counts,</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="logistic-regression.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(hl_cad<span class="sc">$</span>observed, hl_cad<span class="sc">$</span>expected)</span></code></pre></div>
<pre><code>##                 y0 y1     yhat0    yhat1
## [0.0374,0.0657] 20  2 20.711530 1.288470
## (0.0657,0.0875] 18  2 18.368872 1.631128
## (0.0875,0.123]  22  0 19.644094 2.355906
## (0.123,0.136]   24  0 20.787142 3.212858
## (0.136,0.159]   11  2 11.005310 1.994690
## (0.159,0.18]    16  3 15.748367 3.251633
## (0.18,0.205]    14 10 19.208277 4.791723
## (0.205,0.239]   15  3 13.872019 4.127981
## (0.239,0.319]   11  9 14.170991 5.829009
## (0.319,0.652]   12  6  9.483399 8.516601</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>Classification table.</p>
<ul>
<li>Cross-tabulate cad observed cad status vs predicted cad status.</li>
<li>Good model fit if &gt; 70% of the subjects are correctly classified.</li>
</ul></li>
</ol>
<p>We must create probability and predicted cad variables, <code>cad_prob</code> and <code>cad_pred</code>,</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="logistic-regression.html#cb154-1" aria-hidden="true" tabindex="-1"></a>coronary<span class="sc">$</span>cad_prob <span class="ot">=</span> mlg_cad_sel<span class="sc">$</span>fitted.values  <span class="co"># save predicted probabilities</span></span></code></pre></div>
<p>We set cutoff of probability (<code>cad_prob</code>) <span class="math inline">\(\leq\)</span> 0.5 for <code>no cad</code> and probability &gt; 0.5 for <code>cad</code>,</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="logistic-regression.html#cb155-1" aria-hidden="true" tabindex="-1"></a>coronary<span class="sc">$</span>cad_pred <span class="ot">=</span> <span class="fu">ifelse</span>(coronary<span class="sc">$</span>cad_prob <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">&quot;cad&quot;</span>, <span class="st">&quot;no cad&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">as.factor</span>()</span></code></pre></div>
<p>Cross-tabulate <code>cad</code> vs <code>cad_predicted</code>,</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="logistic-regression.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(coronary<span class="sc">$</span>cad, coronary<span class="sc">$</span>cad_pred)</span></code></pre></div>
<pre><code>##         
##          cad no cad
##   no cad   6    157
##   cad      3     34</code></pre>
<p>Then calculate the correctly classified %,</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="logistic-regression.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># correctly classified %</span></span>
<span id="cb158-2"><a href="logistic-regression.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(coronary<span class="sc">$</span>cad <span class="sc">==</span> coronary<span class="sc">$</span>cad_pred) <span class="sc">/</span> <span class="fu">length</span>(coronary<span class="sc">$</span>cad)  <span class="co"># = 80%</span></span></code></pre></div>
<pre><code>## [1] 80</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><p>Area Under the Curve (AUC) of Receiver Operating Characteristics (ROC) curve.</p>
<ul>
<li>It measures the ability of a model to disciminate cad vs non-cad subjects.</li>
<li>AUC is also known as C-statistic (“C” stands for “concordance”).</li>
<li>AUC &gt; 0.7 indicates acceptable model fit.</li>
<li>AUC <span class="math inline">\(\leq\)</span> 0.5 shows no discrimination at all, unaceptable.</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="logistic-regression.html#cb160-1" aria-hidden="true" tabindex="-1"></a>roc_cad <span class="ot">=</span> epiDisplay<span class="sc">::</span><span class="fu">lroc</span>(mlg_cad_sel)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-47-1.png" width="672" /></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="logistic-regression.html#cb161-1" aria-hidden="true" tabindex="-1"></a>roc_cad<span class="sc">$</span>auc  <span class="co"># acceptable</span></span></code></pre></div>
<pre><code>## [1] 0.7320511</code></pre>
<p>The model fulfill 2 out of 3 criteria we set for model fit assessment.</p>
</div>
<div id="interpretation-3" class="section level3" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Interpretation</h3>
<p>Now we have decided on our final model, rename the model,</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="logistic-regression.html#cb163-1" aria-hidden="true" tabindex="-1"></a>mlg_cad_final <span class="ot">=</span> mlg_cad_sel</span></code></pre></div>
<p>and interpret the ORs of the model,</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="logistic-regression.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlg_cad_final)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = cad ~ dbp + gender, family = binomial, data = coronary)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.4520  -0.6508  -0.5249  -0.3643   2.3337  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -6.12046    1.31667  -4.648 3.34e-06 ***
## dbp          0.04950    0.01463   3.383 0.000717 ***
## genderman    0.80573    0.39084   2.062 0.039253 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 191.56  on 199  degrees of freedom
## Residual deviance: 175.20  on 197  degrees of freedom
## AIC: 181.2
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="logistic-regression.html#cb166-1" aria-hidden="true" tabindex="-1"></a>tib_mlg <span class="ot">=</span> <span class="fu">tidy</span>(mlg_cad_final, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>)  <span class="co"># in Odds ratio</span></span></code></pre></div>
<ul>
<li>1mmHg increase in DBP increase the odds of cad by 1.05 times (or 5%), controlling the effect of gender.</li>
<li>Man has 2.24 times odds of cad as compared to woman, controlling for the effect of DBP.</li>
</ul>
<p>Notice that for numerical predictor, it sounds odd to interpret the OR for 1 unit increase. We can obtain the OR for any specific increase in the value (a constant, <span class="math inline">\(c\)</span>), e.g. 5 or 10 unit increase etc. To obtain the OR simply multiply the coefficient <span class="math inline">\(beta\)</span> (careful, not OR) by the needed constant value, <span class="math inline">\(c\)</span>$,
<span class="math display">\[OR = e^{(c \times \beta)}\]</span></p>
<p>To obtain the OR of 10mmHg increase in DBP,
<span class="math display">\[OR_{10\times dbp} = e^{10\times0.05} = e^{0.5} = 1.65\]</span></p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="logistic-regression.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span><span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## [1] 1.648721</code></pre>
<p>or more precisely, directly from our model,</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="logistic-regression.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mlg_cad_final)</span></code></pre></div>
<pre><code>## (Intercept)         dbp   genderman 
## -6.12046337  0.04950439  0.80572747</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="logistic-regression.html#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">10</span><span class="sc">*</span><span class="fu">coef</span>(mlg_cad_final)[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>##     dbp 
## 1.64057</code></pre>
<ul>
<li>10mmHg increase in DBP increase the odds of cad by 1.64 times (or 64%), controlling the effect of gender.</li>
</ul>
<p>We can also obtain <span class="math inline">\(R^2\)</span> for the logistic regression model,</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="logistic-regression.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rsq</span>(mlg_cad_final, <span class="at">adj =</span> T)</span></code></pre></div>
<pre><code>## [1] 0.07257276</code></pre>
<ul>
<li>DBP and gender explains (only) 7.3% variance in cad. This is quite low, which indicates that there are more predictors we should consider to predict cad occurrence.</li>
</ul>
<p><em>Note</em>: R-squared is usually reported for linear regression. But R-squared is also available for GLM, in our case logistic regression. This is usually known as pseudo-R-squared. In GLM, it is made possible by the work of <span class="citation"><a href="#ref-zhang2017" role="doc-biblioref">Zhang</a> (<a href="#ref-zhang2017" role="doc-biblioref">2017</a>)</span>, the author of “rsq” package.</p>
</div>
<div id="model-equations" class="section level3" number="2.5.5">
<h3><span class="header-section-number">2.5.5</span> Model equations</h3>
<p>Our basic logistic regression equation is given by,
<span class="math display">\[log_e\bigg(\frac{p_{cad}}{1-p_{cad}}\bigg) = -6.12 + 0.05 \times\ dbp + 0.81 \times gender\ (man)\]</span></p>
<p>CAD probability is given by,
<span class="math display">\[p_{cad} = \frac{e^{-6.12 + 0.05 \times\ dbp + 0.81 \times gender\ (man)}}{1 + {e^{-6.12 + 0.05 \times\ dbp + 0.81 \times gender\ (man)}}}\]</span>
<em>Note</em>: Again, don’t scratch your head.</p>
</div>
<div id="prediction-1" class="section level3" number="2.5.6">
<h3><span class="header-section-number">2.5.6</span> Prediction</h3>
<p>It is easy to predict in R using our fitted model above. First we view the predicted values for our sample,</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="logistic-regression.html#cb175-1" aria-hidden="true" tabindex="-1"></a>coronary<span class="sc">$</span>cad_prob <span class="ot">=</span> <span class="fu">predict</span>(mlg_cad_final, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)  <span class="co"># in probability</span></span>
<span id="cb175-2"><a href="logistic-regression.html#cb175-2" aria-hidden="true" tabindex="-1"></a><span class="co"># converted from logit, by adding type = &quot;response&quot;</span></span>
<span id="cb175-3"><a href="logistic-regression.html#cb175-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coronary<span class="sc">$</span>cad_prob)</span></code></pre></div>
<pre><code>## [1] 0.05985186 0.09456561 0.12324054 0.23685057 0.24845622 0.14799425</code></pre>
<p>You can also use <code>mlg_cad_final$fitted.values</code> as we did before for <code>cad_prob</code>. But as we will see below, we need predict() for new data, so we need to use the proper <code>predict()</code> function.</p>
<p>Now let us try predicting for a subject,</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="logistic-regression.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dbp = 110, gender = man</span></span>
<span id="cb177-2"><a href="logistic-regression.html#cb177-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mlg_cad_final, <span class="fu">list</span>(<span class="at">dbp =</span> <span class="dv">110</span>, <span class="at">gender =</span> <span class="st">&quot;man&quot;</span>), <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##         1 
## 0.5326403</code></pre>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="logistic-regression.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability &gt; 0.5 = cad</span></span></code></pre></div>
<p>Now for many subjects,</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="logistic-regression.html#cb180-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">dbp =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">110</span>, <span class="dv">120</span>, <span class="dv">100</span>, <span class="dv">110</span>, <span class="dv">120</span>),</span>
<span id="cb180-2"><a href="logistic-regression.html#cb180-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">gender =</span> <span class="fu">c</span>(<span class="st">&quot;man&quot;</span>, <span class="st">&quot;man&quot;</span>, <span class="st">&quot;man&quot;</span>, <span class="st">&quot;woman&quot;</span>, <span class="st">&quot;woman&quot;</span>, <span class="st">&quot;woman&quot;</span>))</span>
<span id="cb180-3"><a href="logistic-regression.html#cb180-3" aria-hidden="true" tabindex="-1"></a>new_data</span></code></pre></div>
<pre><code>##   dbp gender
## 1 100    man
## 2 110    man
## 3 120    man
## 4 100  woman
## 5 110  woman
## 6 120  woman</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="logistic-regression.html#cb182-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mlg_cad_final, new_data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<pre><code>##         1         2         3         4         5         6 
## 0.4099198 0.5326403 0.6515344 0.2368506 0.3373825 0.4551368</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="logistic-regression.html#cb184-1" aria-hidden="true" tabindex="-1"></a>new_data<span class="sc">$</span>prob_cad <span class="ot">=</span> <span class="fu">predict</span>(mlg_cad_final, new_data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb184-2"><a href="logistic-regression.html#cb184-2" aria-hidden="true" tabindex="-1"></a>new_data</span></code></pre></div>
<pre><code>##   dbp gender  prob_cad
## 1 100    man 0.4099198
## 2 110    man 0.5326403
## 3 120    man 0.6515344
## 4 100  woman 0.2368506
## 5 110  woman 0.3373825
## 6 120  woman 0.4551368</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="logistic-regression.html#cb186-1" aria-hidden="true" tabindex="-1"></a>new_data<span class="sc">$</span>pred_cad <span class="ot">=</span> <span class="fu">cut</span>(new_data<span class="sc">$</span>prob_cad, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.5</span>, <span class="cn">Inf</span>),</span>
<span id="cb186-2"><a href="logistic-regression.html#cb186-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;no cad&quot;</span>, <span class="st">&quot;cad&quot;</span>))</span>
<span id="cb186-3"><a href="logistic-regression.html#cb186-3" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative to ifelse</span></span>
<span id="cb186-4"><a href="logistic-regression.html#cb186-4" aria-hidden="true" tabindex="-1"></a>new_data</span></code></pre></div>
<pre><code>##   dbp gender  prob_cad pred_cad
## 1 100    man 0.4099198   no cad
## 2 110    man 0.5326403      cad
## 3 120    man 0.6515344      cad
## 4 100  woman 0.2368506   no cad
## 5 110  woman 0.3373825   no cad
## 6 120  woman 0.4551368   no cad</code></pre>
</div>
</div>
<div id="exercises-1" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Exercises</h2>
<ul>
<li>obtain OR for 5mmHg increase in DBP</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-hosmer2013" class="csl-entry">
Hosmer, D. W., Lemeshow, S., &amp; Sturdivant, R. X. (2013). <em>Applied logistic regression</em>. Wiley. Retrieved from <a href="https://books.google.com.my/books?id=bRoxQBIZRd4C">https://books.google.com.my/books?id=bRoxQBIZRd4C</a>
</div>
<div id="ref-zhang2017" class="csl-entry">
Zhang, D. (2017). A coefficient of determination for generalized linear models. <em>The American Statistician</em>, <em>71</em>(4), 310–316. <a href="https://doi.org/10.1080/00031305.2016.1256839">https://doi.org/10.1080/00031305.2016.1256839</a>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-logistic.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
